# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgConfig.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 352)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.twConfig = QtWidgets.QTabWidget(Dialog)
        self.twConfig.setObjectName("twConfig")
        self.tabIperf = QtWidgets.QWidget()
        self.tabIperf.setObjectName("tabIperf")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabIperf)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.tabIperf)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbHost = QtWidgets.QLabel(self.widget_3)
        self.lbHost.setObjectName("lbHost")
        self.horizontalLayout_2.addWidget(self.lbHost)
        self.leHost = QtWidgets.QLineEdit(self.widget_3)
        self.leHost.setMinimumSize(QtCore.QSize(200, 0))
        self.leHost.setObjectName("leHost")
        self.horizontalLayout_2.addWidget(self.leHost)
        self.lbPort = QtWidgets.QLabel(self.widget_3)
        self.lbPort.setObjectName("lbPort")
        self.horizontalLayout_2.addWidget(self.lbPort)
        self.sbPort = QtWidgets.QSpinBox(self.widget_3)
        self.sbPort.setMinimum(1000)
        self.sbPort.setMaximum(65534)
        self.sbPort.setProperty("value", 5201)
        self.sbPort.setObjectName("sbPort")
        self.horizontalLayout_2.addWidget(self.sbPort)
        self.lbFormat = QtWidgets.QLabel(self.widget_3)
        self.lbFormat.setObjectName("lbFormat")
        self.horizontalLayout_2.addWidget(self.lbFormat)
        self.comboBoxFormat = QtWidgets.QComboBox(self.widget_3)
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxFormat)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.widget_10)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_11 = QtWidgets.QWidget(self.groupBox)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.rbDuration = QtWidgets.QRadioButton(self.widget_11)
        self.rbDuration.setChecked(True)
        self.rbDuration.setObjectName("rbDuration")
        self.horizontalLayout_12.addWidget(self.rbDuration)
        self.sbDuration = QtWidgets.QSpinBox(self.widget_11)
        self.sbDuration.setMinimum(1)
        self.sbDuration.setMaximum(999999999)
        self.sbDuration.setProperty("value", 10)
        self.sbDuration.setObjectName("sbDuration")
        self.horizontalLayout_12.addWidget(self.sbDuration)
        self.lbDurationUnit = QtWidgets.QLabel(self.widget_11)
        self.lbDurationUnit.setObjectName("lbDurationUnit")
        self.horizontalLayout_12.addWidget(self.lbDurationUnit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget_11, 0, 0, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.groupBox)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rbByte = QtWidgets.QRadioButton(self.widget_12)
        self.rbByte.setEnabled(False)
        self.rbByte.setObjectName("rbByte")
        self.horizontalLayout_11.addWidget(self.rbByte)
        self.sbByte = QtWidgets.QSpinBox(self.widget_12)
        self.sbByte.setEnabled(False)
        self.sbByte.setObjectName("sbByte")
        self.horizontalLayout_11.addWidget(self.sbByte)
        self.comboByte = QtWidgets.QComboBox(self.widget_12)
        self.comboByte.setEnabled(False)
        self.comboByte.setEditable(False)
        self.comboByte.setObjectName("comboByte")
        self.comboByte.addItem("")
        self.comboByte.addItem("")
        self.comboByte.addItem("")
        self.horizontalLayout_11.addWidget(self.comboByte)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.gridLayout.addWidget(self.widget_12, 0, 1, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.groupBox)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rbBlocks = QtWidgets.QRadioButton(self.widget_13)
        self.rbBlocks.setEnabled(False)
        self.rbBlocks.setObjectName("rbBlocks")
        self.horizontalLayout_13.addWidget(self.rbBlocks)
        self.spBlocks = QtWidgets.QSpinBox(self.widget_13)
        self.spBlocks.setEnabled(False)
        self.spBlocks.setObjectName("spBlocks")
        self.horizontalLayout_13.addWidget(self.spBlocks)
        self.comboBlocks = QtWidgets.QComboBox(self.widget_13)
        self.comboBlocks.setEnabled(False)
        self.comboBlocks.setEditable(False)
        self.comboBlocks.setObjectName("comboBlocks")
        self.comboBlocks.addItem("")
        self.comboBlocks.addItem("")
        self.comboBlocks.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBlocks)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_13, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbParallel = QtWidgets.QLabel(self.widget_4)
        self.lbParallel.setObjectName("lbParallel")
        self.horizontalLayout_3.addWidget(self.lbParallel)
        self.spParallel = QtWidgets.QSpinBox(self.widget_4)
        self.spParallel.setProperty("value", 1)
        self.spParallel.setDisplayIntegerBase(12)
        self.spParallel.setObjectName("spParallel")
        self.horizontalLayout_3.addWidget(self.spParallel)
        self.cbReverse = QtWidgets.QCheckBox(self.widget_4)
        self.cbReverse.setObjectName("cbReverse")
        self.horizontalLayout_3.addWidget(self.cbReverse)
        self.lbWindow = QtWidgets.QLabel(self.widget_4)
        self.lbWindow.setObjectName("lbWindow")
        self.horizontalLayout_3.addWidget(self.lbWindow)
        self.sbWindowSize = QtWidgets.QSpinBox(self.widget_4)
        self.sbWindowSize.setSuffix("")
        self.sbWindowSize.setMaximum(65535)
        self.sbWindowSize.setObjectName("sbWindowSize")
        self.horizontalLayout_3.addWidget(self.sbWindowSize)
        self.comboWindowSizeUnit = QtWidgets.QComboBox(self.widget_4)
        self.comboWindowSizeUnit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.comboWindowSizeUnit.setObjectName("comboWindowSizeUnit")
        self.comboWindowSizeUnit.addItem("")
        self.comboWindowSizeUnit.addItem("")
        self.comboWindowSizeUnit.addItem("")
        self.horizontalLayout_3.addWidget(self.comboWindowSizeUnit)
        self.lbMTU = QtWidgets.QLabel(self.widget_4)
        self.lbMTU.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbMTU.setObjectName("lbMTU")
        self.horizontalLayout_3.addWidget(self.lbMTU)
        self.sbMTU = QtWidgets.QSpinBox(self.widget_4)
        self.sbMTU.setMaximum(65535)
        self.sbMTU.setProperty("value", 40)
        self.sbMTU.setObjectName("sbMTU")
        self.horizontalLayout_3.addWidget(self.sbMTU)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_bitrate = QtWidgets.QLabel(self.widget)
        self.lb_bitrate.setObjectName("lb_bitrate")
        self.horizontalLayout_7.addWidget(self.lb_bitrate)
        self.sbBitrate = QtWidgets.QSpinBox(self.widget)
        self.sbBitrate.setObjectName("sbBitrate")
        self.horizontalLayout_7.addWidget(self.sbBitrate)
        self.comboBitrateUnit = QtWidgets.QComboBox(self.widget)
        self.comboBitrateUnit.setObjectName("comboBitrateUnit")
        self.comboBitrateUnit.addItem("")
        self.comboBitrateUnit.addItem("")
        self.comboBitrateUnit.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBitrateUnit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gbProtocal = QtWidgets.QGroupBox(self.widget_5)
        self.gbProtocal.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gbProtocal.setFlat(False)
        self.gbProtocal.setCheckable(False)
        self.gbProtocal.setObjectName("gbProtocal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbProtocal)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbTCP = QtWidgets.QRadioButton(self.gbProtocal)
        self.rbTCP.setChecked(True)
        self.rbTCP.setObjectName("rbTCP")
        self.horizontalLayout.addWidget(self.rbTCP)
        self.rbUDP = QtWidgets.QRadioButton(self.gbProtocal)
        self.rbUDP.setChecked(False)
        self.rbUDP.setObjectName("rbUDP")
        self.horizontalLayout.addWidget(self.rbUDP)
        self.horizontalLayout_4.addWidget(self.gbProtocal)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.twConfig.addTab(self.tabIperf, "")
        self.tabTurnTable = QtWidgets.QWidget()
        self.tabTurnTable.setObjectName("tabTurnTable")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabTurnTable)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.tabTurnTable)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbTurnTable = QtWidgets.QCheckBox(self.widget_6)
        self.cbTurnTable.setMinimumSize(QtCore.QSize(0, 0))
        self.cbTurnTable.setObjectName("cbTurnTable")
        self.horizontalLayout_5.addWidget(self.cbTurnTable)
        self.comboComPort = QtWidgets.QComboBox(self.widget_6)
        self.comboComPort.setObjectName("comboComPort")
        self.horizontalLayout_5.addWidget(self.comboComPort)
        self.comboBaulRate = QtWidgets.QComboBox(self.widget_6)
        self.comboBaulRate.setObjectName("comboBaulRate")
        self.horizontalLayout_5.addWidget(self.comboBaulRate)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.tabTurnTable)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.ttStart = QtWidgets.QSpinBox(self.widget_7)
        self.ttStart.setMaximum(360)
        self.ttStart.setSingleStep(10)
        self.ttStart.setObjectName("ttStart")
        self.horizontalLayout_9.addWidget(self.ttStart)
        self.label = QtWidgets.QLabel(self.widget_7)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.ttEnd = QtWidgets.QSpinBox(self.widget_7)
        self.ttEnd.setMaximum(360)
        self.ttEnd.setSingleStep(10)
        self.ttEnd.setProperty("value", 360)
        self.ttEnd.setObjectName("ttEnd")
        self.horizontalLayout_9.addWidget(self.ttEnd)
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.ttStep = QtWidgets.QSpinBox(self.widget_7)
        self.ttStep.setMaximum(360)
        self.ttStep.setSingleStep(5)
        self.ttStep.setProperty("value", 30)
        self.ttStep.setObjectName("ttStep")
        self.horizontalLayout_9.addWidget(self.ttStep)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_5.addWidget(self.widget_7)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.twConfig.addTab(self.tabTurnTable, "")
        self.verticalLayout.addWidget(self.twConfig)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.twConfig.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbHost.setText(_translate("Dialog", "Host(-c):"))
        self.leHost.setText(_translate("Dialog", "127.0.0.1"))
        self.lbPort.setText(_translate("Dialog", "Port(-p)"))
        self.lbFormat.setText(_translate("Dialog", "format(-f):"))
        self.comboBoxFormat.setCurrentText(_translate("Dialog", "k"))
        self.comboBoxFormat.setItemText(0, _translate("Dialog", "k"))
        self.comboBoxFormat.setItemText(1, _translate("Dialog", "m"))
        self.comboBoxFormat.setItemText(2, _translate("Dialog", "g"))
        self.comboBoxFormat.setItemText(3, _translate("Dialog", "t"))
        self.comboBoxFormat.setItemText(4, _translate("Dialog", "K"))
        self.comboBoxFormat.setItemText(5, _translate("Dialog", "M"))
        self.comboBoxFormat.setItemText(6, _translate("Dialog", "G"))
        self.comboBoxFormat.setItemText(7, _translate("Dialog", "T"))
        self.groupBox.setTitle(_translate("Dialog", "Duration:"))
        self.rbDuration.setText(_translate("Dialog", "Duration(-t):"))
        self.lbDurationUnit.setText(_translate("Dialog", "sec"))
        self.rbByte.setText(_translate("Dialog", "(TODO)Byte transmit(-n):"))
        self.comboByte.setItemText(0, _translate("Dialog", "K"))
        self.comboByte.setItemText(1, _translate("Dialog", "M"))
        self.comboByte.setItemText(2, _translate("Dialog", "G"))
        self.rbBlocks.setText(_translate("Dialog", "(TODO)Blocks to transmit(-k)"))
        self.comboBlocks.setItemText(0, _translate("Dialog", "K"))
        self.comboBlocks.setItemText(1, _translate("Dialog", "M"))
        self.comboBlocks.setItemText(2, _translate("Dialog", "G"))
        self.lbParallel.setText(_translate("Dialog", "Parallel(-P):"))
        self.cbReverse.setText(_translate("Dialog", "Reverse(-R)"))
        self.lbWindow.setText(_translate("Dialog", "Window Size(-w):"))
        self.sbWindowSize.setToolTip(_translate("Dialog", "<html><head/><body><p>set window size / socket buffer size</p><p>Use 0 to not specify this option</p></body></html>"))
        self.comboWindowSizeUnit.setItemText(0, _translate("Dialog", "K"))
        self.comboWindowSizeUnit.setItemText(1, _translate("Dialog", "M"))
        self.comboWindowSizeUnit.setItemText(2, _translate("Dialog", "G"))
        self.lbMTU.setText(_translate("Dialog", "MTU(-M):"))
        self.sbMTU.setToolTip(_translate("Dialog", "set TCP/SCTP maximum segment size (MTU - 40 bytes)"))
        self.lb_bitrate.setToolTip(_translate("Dialog", "<html><head/><body><p>target bitrate in bits/sec (0 for unlimited)</p><p>(default 1 Mbit/sec for UDP, unlimited for TCP)</p></body></html>"))
        self.lb_bitrate.setText(_translate("Dialog", "bitrate (-b)"))
        self.comboBitrateUnit.setItemText(0, _translate("Dialog", "K"))
        self.comboBitrateUnit.setItemText(1, _translate("Dialog", "M"))
        self.comboBitrateUnit.setItemText(2, _translate("Dialog", "G"))
        self.gbProtocal.setTitle(_translate("Dialog", "Protocal:"))
        self.rbTCP.setText(_translate("Dialog", "TCP"))
        self.rbUDP.setText(_translate("Dialog", "UDP(-u)"))
        self.twConfig.setTabText(self.twConfig.indexOf(self.tabIperf), _translate("Dialog", "Iperf"))
        self.cbTurnTable.setText(_translate("Dialog", "Use TurnTable"))
        self.label_3.setText(_translate("Dialog", "degree:"))
        self.label.setText(_translate("Dialog", "-"))
        self.label_2.setText(_translate("Dialog", "Step:"))
        self.twConfig.setTabText(self.twConfig.indexOf(self.tabTurnTable), _translate("Dialog", "TurnTable"))

